baseURL = 'https://blog.adultra.riccardopedrielli.com/'
languageCode = 'en-us'
title = 'Adultra blog'
theme = "jeffprod"

[permalinks]
post = "/:year/:filename"

[taxonomies]
tag = "tags"
archive = "archives"
